stages:
  - build

variables:
  REGISTRY: "136204750825.dkr.ecr.ap-southeast-1.amazonaws.com"
  REGISTRY_NAMESPACE: "frontend"
  REGISTRY_USER: "AWS"
  IMAGE_CLEAN: "true"
  BUILD_LIST: '[{"name": "order-system"}]'

before_script:
- |
  echo "CI_COMMIT_SHA: ${CI_COMMIT_SHA}"
  echo "CI_COMMIT_TAG: ${CI_COMMIT_TAG}"
  echo "CI_COMMIT_REF_NAME: ${CI_COMMIT_REF_NAME}"

build:
  only:
  - master
  stage: build
  image: zgwldrc/build-helper
  script:
  - build
